name: kubrow_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.78.0
  freezed_annotation: ^2.2.0
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^8.0.2
  build_runner: ^2.4.5
  freezed: ^2.3.5

flutter:
  uses-material-design: true